
version: '3'
networks:
  default:
    name: traefik_default
    external: true
  
services:
  db:
    image: "mariadb:10.5"
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_UNAME}
      - MYSQL_PASSWORD=${DB_PASS}
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "5433:3306"
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=mysql://${DB_UNAME}:${DB_PASS}@db:5433/${DB_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-qinbeansnet.rule=Host(`api.qinbeans.net`)"
      - "traefik.http.middlewares.backend-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.backend-cors.headers.accesscontrolalloworiginlist=https://qinbeans.net"
      - "traefik.http.middlewares.backend-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.backend-cors.headers.addvaryheader=true"
      - "traefik.http.routers.backend-qinbeansnet.entrypoints=websecure"
      - "traefik.http.routers.backend-qinbeansnet.tls=true"
      - "traefik.http.routers.backend-qinbeansnet.tls.certresolver=cf"
      - "traefik.http.services.backend-qinbeansnet.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.service.middlewares=backend-cors"
volumes:
  db: