<!-- Login shows the typical username/password form, but the pw is generated by the backend during startup -->
<script lang="ts">
    import { submit_credentials, new_credentials } from "../../ts/credentials";
    import { updateClient } from "../../ts/utils";
    import { current } from "../../ts/store"
    import init, { update_url } from "../../wasm-lib/pkg";
    const submit = (e:any) => {
        //submit form
        //grab id human
        let human = (<HTMLInputElement>document.getElementById("human")).checked
        if(!human){
            alert("You aren't a human")
            return
        }
        e.preventDefault()
        const creds = new_credentials((<HTMLInputElement>document.getElementById("username")).value, (<HTMLInputElement>document.getElementById("token")).value)
        submit_credentials(creds)
    }

    const go_home = () => {
        current.update((x) => {
            x.state = 0
            return x
        })
        updateClient()
        init().then(() => {
            update_url(0, true)
        })
    }

    const home = "<- Home"
</script>

<div class="w-fit h-fit dark:bg-black bg-gray-500 bg-opacity-75 dark:bg-opacity-75 rounded-lg pl-5 pr-5 pb-1.5">
    <div class="text-4xl sm:text-2xl text-pink-500">Login</div>
    <!-- expect a response with a token, else send back here with a warning -->
    <div class="grid grid-cols-1 place-content-center gap-1.5 text-3xl sm:text-xl">
        <!-- Username -->
        <label for="username">Username</label>
        <input class="pl-1.5 pr-1.5 rounded-lg dark:bg-gray-700 bg-gray-300" id="username" type="text" name="username" placeholder="Username">
        <!-- Token -->
        <label for="token">Token</label>
        <input class="pl-1.5 pr-1.5 rounded-lg dark:bg-gray-700 bg-gray-300" id="token" type="password" name="token" placeholder="Token">
        <!-- Submit -->
        <div class="flex justify-center">
            <label class="w-fit form-control" for="human">
                I Am Human
                <input class="checkbox bg-pink-500" type="checkbox" name="human" id="human" value="human">
            </label>
        </div>
        <input class="shadow cursor-pointer pl-1.5 pr-1.5 rounded-lg dark:bg-gray-700 bg-gray-300 text-pink-500 hover:border-2 border-solid border-pink-500" type="submit" value="Login" on:click={submit}>
    </div>
</div>
<div class="flex justify-center m-10 sm:m-2">
    <div class="shadow cursor-pointer pl-1.5 pr-1.5 rounded-lg dark:bg-gray-700 bg-gray-300 text-pink-500 hover:border-2 border-solid border-pink-500 w-fit h-fit" on:click={go_home}>
        {home}
    </div>
</div>