<!-- Login shows the typical username/password form, but the pw is generated by the backend during startup -->
<script lang="ts">
    import { submit_credentials, new_credentials } from "../../ts/credentials";
    const mode = import.meta.env.MODE
    const submit = (e:any) => {
        //submit form
        e.preventDefault()
        const creds = new_credentials((<HTMLInputElement>document.getElementById("username")).value, (<HTMLInputElement>document.getElementById("token")).value)
        submit_credentials(creds,mode)
    }
</script>

<div class="w-fit h-fit bg-black bg-opacity-75 rounded-lg pl-5 pr-5 pb-1.5">
    <div class="text-2xl text-pink-500">Login</div>
    <!-- expect a response with a token, else send back here with a warning -->
    <div class="grid grid-cols-1 place-content-center gap-1.5">
        <!-- Username -->
        <label for="username">Username</label>
        <input class="pl-1.5 pr-1.5 rounded-lg bg-gray-700" id="username" type="text" name="username" placeholder="Username">
        <!-- Token -->
        <label for="token">Token</label>
        <input class="pl-1.5 pr-1.5 rounded-lg bg-gray-700" id="token" type="password" name="token" placeholder="Token">
        <!-- Submit -->
        <input class="cursor-pointer pl-1.5 pr-1.5 rounded-lg bg-gray-700 text-pink-500" type="submit" value="Login" on:click={submit}>
    </div>
</div>