<!-- Login shows the typical username/password form, but the pw is generated by the backend during startup -->
<script lang="ts">
    import { submit_credentials, new_credentials } from "./ts/credentials";
    const mode = import.meta.env.MODE
    const submit = (e:any) => {
        //submit form
        e.preventDefault()
        const creds = new_credentials(document.getElementById("username").value, document.getElementById("token").value)
        submit_credentials(creds,mode)
    }
</script>

<div class="m-grid">
    <h1 class="h1 x-9 y-1">Login</h1>
    <!-- expect a response with a token, else send back here with a warning -->
    <div class="x-9 y-15">
        <!-- Username -->
        <label for="username">Username</label>
        <input class="input bubble" id="username" type="text" name="username" placeholder="Username">
        <!-- Token -->
        <label for="token">Token</label>
        <input class="input bubble" id="token" type="password" name="token" placeholder="Token">
        <!-- Submit -->
        <input class="submit" type="submit" value="Login" on:click={submit}>
    </div>
</div>