#based on Node JS, adapted for Bun

name: Svelte CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
defaults:
  run:
    working-directory: frontend
      
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Bun
      # You may pin to the exact commit or the version.
      # uses: xHyroM/setup-bun@a0f9c413e5da19211e83c1248fad43dd2a466ce9
      uses: xHyroM/setup-bun@v0.1.4
    - run: bun install
    - run: bun run build
    - name: Testing Svelte with Wiptest
    - run: bun wiptest
