#based on Node JS, adapted for Bun

name: Svelte CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
defaults:
  run:
    working-directory: frontend
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: ["latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bun
      uses: xHyroM/setup-bun@v0.1.3
      with:
        bun-version: ${{ matrix.bun-version }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        misc-test-builds: false
    - name: Install
      run: bun install
    - name: Build
      run: bun run build
    - name: Test
      run: bun wiptest
