#based on Node JS, adapted for Bun

name: Svelte CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
defaults:
  run:
    working-directory: frontend
      
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Bun
      uses: xHyroM/setup-bun@v0.1.4
    - name: Installing dependencies
      run: bun install
    - name: Building
      run: bun run build
    - name: Testing
      run: bun wiptest
