#based on Node JS, adapted for Bun

name: Svelte CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
defaults:
  run:
    working-directory: frontend
      
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Bun latest
    - uses: xhyrom/setup-bun@v0.1.3
      with:
        bun-version: latest
    - run: bun install
    - run: bun run build
    - name: Testing Svelte with Wiptest
    - run: bun wiptest
