# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Svelte CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: ["latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bun
      uses: xHyroM/setup-bun@v0.1.7
      with:
        bun-version: ${{ matrix.bun-version }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        misc-test-builds: false
    - run: bun install
    - run: bun run astro build
